### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/Taken-Map#1]
## World Objects
- [ ] Turtles
- [x] Block decoration: colour particular blocks
- [ ] Mutable map: add blocks whilst playing.
- [x] Player state: blocks which kill you when you aren't a particular colour.
- [ ] Teleporters - how do I prevent abuse?
- [ ] User provided maps
- [x] More variety in the world.
## UX
- [ ] Save progress
- [ ] Tutorial & documentation
- [x] Better error handling: also handling deaths correctly.
## Editor
- [ ] Moving about with right click
- [ ] Text selection
- [ ] Switch to computer?
- [x] Use `term.blit` to reduce flicker.

**Comment by SquidDev** [comment]
For 0.3:

- Turtles!
- Documentation.
- Use computer to edit instead.
- Save progress and give option to resume or start anew.
