### ISSUE TITLE
0.3 todo list

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/Taken-Map#3]
- [ ] Turtles!
- [ ] Documentation.
- [ ] Use computer to edit instead.
- [x] Save progress
  - [ ] Selection menu when launching to jump to level
- [x] Convert to single script
- [ ] Handle starving & dropping pocket computer (though not needed if we use computer as above)
